### ISSUE TITLE
Dock do'nt show icons.

### ISSUE THREAD

**Issue by alphamodh0** [helloSystem/Dock#27] opened 2021-12-11 21:18 UTC
The dock does not display most of the application icons. For example: Installing Chromium shows the icon, but then opening it shows the following:
![dock error](https://user-images.githubusercontent.com/90866187/145691923-b1a6865d-7bf8-48e1-b089-dd36d0124357.png)

**Comment by probonopd** [comment] 2021-12-12 17:08
Duplicate of https://github.com/helloSystem/Dock/issues/26

**Closed as completed by probonopd** 2021-12-12 17:08 UTC
